In [2]:
import numpy as np

### Gauss-Jordan Elimination 
---
See the textbook or [this link](https://brilliant.org/wiki/gaussian-elimination/) for explanation of terminology and examples.

In [19]:
# Gauss-Jordan Elimination (without row-swapping)
def findRREF(A):
    '''
    Input: a general rectangular matrix
    Output: the row reduced echelon form of the matrix A 
    by using Gauss-Jordan elimination
    '''
    augA = np.copy(A)
    m,n=augA.shape
    print("Augmented matrix: ",augA)
    determinant = 1.0
    for k in range(m):
        # Check that the matrix is not rank deficient
        if np.abs(augA[k,k]) < 10**(-15):
            exit("The given matrix is singular or requires row swapping")
        # Convert the pivot element to 1
        determinant *= augA[k, k]
        augA[k,:] = augA[k,:] /augA[k,k]

        for i in range(m):
            if i==k:
                continue
            z = -augA[i,k]
            # Change the entire rows (k+1)st onward
            augA[i,:] = augA[i,:] + z*augA[k,:] 
        print("Pass {}:\n".format(k+1))
        print(augA)
    return augA,determinant

In [18]:
def invByRREF(A):
    m,n=A.shape
    if m!=n:
        exit("To find inverse, please provide a square matrix only.")
    # Appropriate augmented matrix. One line
    augA = # Your code here 
    modified_augA = findRREF(augA)
    # Take appropriate slice of modified_augA for inverse
    invA = # Your code here
    return invA

#### Example: Solve the following system
$$
\begin{bmatrix}
2 & 4 & 0 \\
5 & -2 & 6 \\
3 & 1 & -2 \\
\end{bmatrix}\ \begin{bmatrix}
x_1\\x_2\\x_3
\end{bmatrix}=\begin{bmatrix}
6\\9\\2
\end{bmatrix}
$$

In [14]:
np.set_printoptions(precision=4)
A = np.array([[2,4,0,6],
             [5,-2,6,9],
             [3,1,-2,2]],dtype=float)
augA_modified = findRREF(A)
# The last column is the solution
soln = augA_modified[:,3:]
print("\n The Solution is \n",soln)

Pass 1:

[[ 1.  2.  0.  3.]
 [ 5. -2.  6.  9.]
 [ 3.  1. -2.  2.]]
Pass 2:

[[ 1.   2.   0.   3. ]
 [-0.   1.  -0.5  0.5]
 [ 0.  -5.  -2.  -7. ]]
Pass 3:

[[ 1.   0.   1.   2. ]
 [-0.   1.  -0.5  0.5]
 [-0.  -0.   1.   1. ]]

 The Solution is 
 [[1.]
 [1.]
 [1.]]


In [6]:
np.set_printoptions(precision=4)
A = np.array([[2,4,0, 1, 0, 0],
             [0,3,6,0,1,0],
             [0,0,1,0,0,1]],dtype=float)
print("\n The Inverse is \n",findRREF(A)[:,3:])

Pass 1:

[[1.  2.  0.  0.5 0.  0. ]
 [0.  3.  6.  0.  1.  0. ]
 [0.  0.  1.  0.  0.  1. ]]
Pass 2:

[[1.     2.     0.     0.5    0.     0.    ]
 [0.     1.     2.     0.     0.3333 0.    ]
 [0.     0.     1.     0.     0.     1.    ]]
Pass 3:

[[ 1.      0.     -4.      0.5    -0.6667  0.    ]
 [ 0.      1.      2.      0.      0.3333  0.    ]
 [ 0.      0.      1.      0.      0.      1.    ]]

 The Inverse is 
 [[ 0.5    -0.6667  4.    ]
 [ 0.      0.3333 -2.    ]
 [ 0.      0.      1.    ]]


**Question**: Can you modify the code for Gauss-Jordan elimination to do the following?
1. Solve a square system $A{\bf x}={\bf b}$
1. Find the inverse of a matrix
1. Find the determinant of a matrix
1. Find the rank of a matrix